
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `hr_bansystem` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`Steam` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`License` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`License2` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	`IP` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`Discord` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Xbox` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Live` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Tokens` LONGTEXT NOT NULL COLLATE 'utf8mb4_bin',
	`Reason` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_bin',
	`isBanned` INT(11) NOT NULL DEFAULT '0',
	`Expire` INT(11) NOT NULL DEFAULT '0',
	INDEX `ID` (`ID`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

